# Generated by Django 5.2.8 on 2025-11-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slovo', models.CharField(max_length=200, verbose_name='слово')),
                ('perevod', models.CharField(max_length=200, verbose_name='перевод')),
            ],
            options={
                'verbose_name': 'слово',
                'verbose_name_plural': 'слова',
            },
        ),
    ]
