# Generated by Django 5.2.8 on 2025-11-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='status',
            field=models.CharField(choices=[('na_izuchenii', 'На изуечнии'), ('izucheno', 'Изучено')], default='na_izuchenii', max_length=20, verbose_name='статус'),
        ),
    ]
