# Generated by Django 5.2.8 on 2025-11-28 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_word_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='word',
            unique_together={('slovo', 'perevod')},
        ),
    ]
