# Generated by Django 5.2.8 on 2025-11-28 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_word_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zametka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000, verbose_name='текст заметки')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zametki', to='core.word', verbose_name='слово')),
            ],
            options={
                'verbose_name': 'заметка',
                'verbose_name_plural': 'заметки',
            },
        ),
    ]
