# Generated by Django 5.2.8 on 2025-12-12 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_zametka'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='profile',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='users.profile', verbose_name='профиль пользователя'),
            preserve_default=False,
        ),
    ]
