# Generated by Django 5.2.8 on 2025-12-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_word_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikesCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='имя')),
                ('slug', models.SlugField(unique=True, verbose_name='кодовое название')),
                ('count', models.IntegerField(default=0, verbose_name='количество спасибок')),
            ],
            options={
                'verbose_name': 'счетчик спасибок',
                'verbose_name_plural': 'счетчики спасибок',
            },
        ),
    ]
